### ISSUE TITLE
Project doesn't compile due to the type keyword being used and call to shaderModule.compilationInfo

### ISSUE THREAD

**Issue by XxAdi101xX** [Twinklebear/webgpu-volume-pathtracer#1]
Seems like the `type` keyword in the shaders.wgsl file are causing compilation errors, seems like a relatively recent issue.
```
type float2 = vec2<f32>;
type float3 = vec3<f32>;
type float4 = vec4<f32>;
type uint2 = vec2<u32>;
type int2 = vec2<i32>;
```
I was able to resolve this locally by removing these lines and replacing all instances with their full form

Additionally, the call to `shaderModule.compilationInfo ` was erroring out so I commented out the following section in `volume-pathtracer.js`:
```
var compilationInfo = await shaderModule.compilationInfo();
if (compilationInfo.messages.length > 0) {
    var hadError = false;
    console.log("Shader compilation log:");
    for (var i = 0; i < compilationInfo.messages.length; ++i) {
        var msg = compilationInfo.messages[i];
        console.log(`${msg.lineNum}:${msg.linePos} - ${msg.message}`);
        hadError = hadError || msg.type == "error";
    }
    if (hadError) {
        console.log("Shader failed to compile");
        return;
    }
}
```
Doing these two things fixed the compilation issues locally.

**Comment by XxAdi101xX** [comment]
Actually never mind, I had the WebGPU Developer Features enabled on chrome. Disabling this flag resolved the issue for me, wonder why that caused issues in the first place.

**Comment by Twinklebear** [comment]
Good to hear you got it working! I think at some point I do need to change to use the `alias` keyword instead of `type`: https://www.w3.org/TR/WGSL/#type-aliases
