### ISSUE TITLE
Looking on Documentation for this project.

### ISSUE THREAD

**Issue by kmilo9999** [Twinklebear/webgpu-volume-pathtracer#2]
Do you have any blog or documentation on how your algorithm works?

**Comment by Twinklebear** [comment]
I don't have a blog post written about it, but that's a good idea! The sampling algorithm used is called Woodcock sampling (or Woodcock tracking, or Delta tracking). PBRTv3 has info about it online: https://pbr-book.org/3ed-2018/Light_Transport_II_Volume_Rendering/Sampling_Volume_Scattering#HeterogeneousMedium , PBRTv4 might also have some good info.

The renderer works by using Woodcock sampling to find where the ray scatters off of a volume particle (see PBRTv3 for how Woodcock sampling works here) : https://github.com/Twinklebear/webgpu-volume-pathtracer/blob/main/src/shaders.wgsl#L272 . This "hit point" is then shaded by using the same Woodcock/delta tracking to compute the transmittance https://github.com/Twinklebear/webgpu-volume-pathtracer/blob/main/src/shaders.wgsl#L296-L298 to the scattering location. For the shading I just use delta tracking, which sees if it samples another scattering point from the hit point to the light, same as in the initial Woodcock sampling step. If we found a scattering point, it's shadowed, if not, it's not shadowed. Finally a random direction on the sphere is sampled to scatter the ray along: https://github.com/Twinklebear/webgpu-volume-pathtracer/blob/main/src/shaders.wgsl#L308 , and the new ray is traced again using Woodcock sampling to find a new scatter point.
